# Generated by Django 4.2.2 on 2023-06-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_events_remove_membershiprequest_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(default=0),
        ),
    ]
