# Generated by Django 4.2.2 on 2023-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_events_event_date_events_eventdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('graduation_year', models.IntegerField(default=0, verbose_name='Graduation Year')),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('profilePhoto', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
