# Generated by Django 4.2.2 on 2023-06-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiprequest',
            name='graduation_year',
            field=models.IntegerField(verbose_name='Graduation Year'),
        ),
    ]
