# Generated by Django 4.2.2 on 2023-06-20 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_events_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_date',
        ),
        migrations.AddField(
            model_name='events',
            name='eventDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='events',
            name='eventTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
